on:
  pull_request:
    types: [review_requested]
jobs:
  notify:
    runs-on: ubuntu-latest
    name: notify chat
    steps:
    - name: Google Chat Notification
      uses: Co-qn/google-chat-notification@releases/v1
      with:
        name: ${GITHUB_REF##*/}
        url: ${{ secrets.GOOGLE_CHAT_WEBHOOK_PR }}
        status: ${{ job.status }}
      if: always()
     